[package]
authors = ["Katharina Thöle <@katharinathoele>", "Lyx Rothböck <@Lypsilonx>"]
categories = ["layout"]
compiler = "0.13.0"
description = "Protokollvorlage für AStA-Sitzungen der Hochschule Darmstadt. Fork von quick-minutes."
disciplines = ["business", "communication", "education", "journalism", "law"]
entrypoint = "asta-minutes.typ"
exclude = ["name-test.typ", "quick-minutes.typ"]
keywords = ["protocol", "minutes", "asta", "hochschule", "sitzungsprotokoll"]
license = "MIT"
name = "quick-asta"
repository = "https://github.com/Lypsilonx/quick-minutes"
version = "0.1.0"

[workspace]
font-paths = ["font"]

[template]
entrypoint = "main.typ"
path = "template"
thumbnail = "thumbnail.png"
